server:
  port: 8083
  servlet:
    context-path: /order
spring:
  application:
    name: order
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
management:
  tracing:
    sampling:
      probability: 1.0  # Sample all requests
  zipkin:
    tracing:
      enabled: true
      base-url: http://localhost:9411/api/v2/spans
